apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iixp3uqyt-go
  janus-idp.io/tekton: iixp3uqyt-go
  backstage.io/kubernetes-id: iixp3uqyt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iixp3uqyt-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
