apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iixp3uqyt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iixp3uqyt-go 
  name: iixp3uqyt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iixp3uqyt-go 
